name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.8'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets for production
        run: npm run build
      
      - name: Optimize Laravel for production
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize
      
      - name: Clean up unnecessary directories
        run: rm -rf node_modules

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.DEPLOY_FTP_SERVER }}
          username: ${{ secrets.DEPLOY_FTP_USERNAME }}
          password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            .env
            database.sqlite
            **/.git*
            **/.git*/**
            **/node_modules/**
          timeout: 60000